##端口
server:
  port: 9988
  connection-timeout: 18000000


spring:
#mySql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Dwzc_123@
    url: jdbc:mysql://118.190.172.69:3306/bishe?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
# mybatis
mybatis:
  mapper-locations: classpath:com/bishe/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.bishe.entity

